id: 151466dc820e465eb1e6bfd20e182310
initial_creation_type: TMX
origin_type: translation
source_metadata:
  id: ''
  title: Toh_101-Upholding_the_Roots_of_Virtue-v2
  language: bo
  author: ''
  volume: {}
